name: CI Backend

on:
  push:
    branches: [ main, ci-cd ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  pull_request:
    branches: [ main, ci-cd ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Set DATABASE_URL
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Validate Prisma schema
      run: npx prisma validate

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run linter
      run: npm run lint
      continue-on-error: true

    - name: Run tests
      run: npx dotenv -e .env -- npm test
      continue-on-error: true

    - name: Build project
      run: npm run build

    - name: Security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
